### ISSUE TITLE
i915 driver times out during drm initialization causing 30s delay in boot to login prompt 

### ISSUE THREAD

**Issue by whbruce** [01org/linux-intel-4.9#13]
Observed behavior
------------------
When booting a Yocto 2.3.1 built image on CherryTrail hardware with linux-intel 4.9.30, drm driver times out during initialization
```
[    5.539880] sd 0:0:0:0: [sda] Attached SCSI removable disk
[   14.933791] [drm:drm_atomic_helper_commit_cleanup_done] *ERROR* [CRTC:42:pipe B] flip_done timed out
[   14.952792] Console: switching to colour frame buffer device 240x67
[   25.685447] [drm:drm_atomic_helper_commit_cleanup_done] *ERROR* [CRTC:42:pipe B] flip_done timed out
[   35.925117] [drm:drm_atomic_helper_commit_cleanup_done] *ERROR* [CRTC:42:pipe B] flip_done timed out
[   37.041314] i915 0000:00:02.0: fb0: inteldrmfb frame buffer device

```
This appears to be a known kernel bug: https://bugs.freedesktop.org/show_bug.cgi?id=98810.

Expected behavior
------------------
Boots to login prompt without delay.

Steps to re-create
------------------
```
$ git clone -b pyro git://git.yoctoproject.org/poky
$ git clone -b pyro git://git.yoctoproject.org/meta-intel
$ source poky/oe-init-build-env
$ bitbake-layers add-layer ../meta-intel
$ echo 'MACHINE = "intel-corei7-64"' >> conf/local.conf
$ bitbake core-image-base
$ sudo dd if=tmp/deploy/images/intel-corei7-64/core-image-base-intel-corei7-64.wic of=/dev/sdd bs=1MB
$ sync
```
Now boot hardware with wic image. Observe 30s delay in getting to login prompt. See [kernel log](https://bugzilla.yoctoproject.org/attachment.cgi?id=3952) and [Yocto bug 11982](https://bugzilla.yoctoproject.org/show_bug.cgi?id=11982)

Workaround
----------
Use linux-yocto kernel that sets version to 4.10.17.
`$ echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-yocto"' >> conf/local.conf`
Build re-build image and boot hardware with wic image. Observe no extra delay in getting to login prompt.

**Comment by pkushwah3** [comment]
CherryTrail is not supported by production kernel team and our integration test doesn't cover any CHT based hardware.
 If this issue can be reproduced on Joule or GP, we will debug further

**Comment by whbruce** [comment]
Disappointing to hear that CherryTrail is not supported. Will advise Intel Aero team against adopting production kernel.

BTW, what is "GP" ?

**Comment by pkushwah3** [comment]
GP: Gordon Peak
