### ISSUE TITLE
32-bit kernel fails to boot

### ISSUE THREAD

**Issue by clsulliv** [01org/linux-intel-4.9#14]
As of 39b77977c62ba675d1b1a46746ff5ef2242089b0, which is release 2017w39.3-103200, we can no longer boot a 32-bit kernel. There is no output whatsoever past the bootloader stage. This is reproducible on the MinnowBoard Max and in qemu, and likely anything else able to run in 32-bit.

Reverting to 2d533948da0a7c53a0a662d3764be166ba996d93, release 2017w38.5-155800, we no longer have this issue.

**Comment by pkushwah3** [comment]
please verify with release LTS Release v4.9.47 2017w41.1-132900 6821d11bb30fd7cf2af394eb54230a0080d3ca96

**Comment by clsulliv** [comment]
It works again with 6821d11bb30fd7cf2af394eb54230a0080d3ca96.
Thanks.
