### ISSUE TITLE
RealSense SR300 support

### ISSUE THREAD

**Issue by ipuustin** [01org/linux-intel-4.9#2]
Right now this linux-intel doesn't support the depth channel of Intel RealSense SR300 camera. There are non-merged patches available for enabling depth channel support: https://patchwork.linuxtv.org/patch/39697/ and https://patchwork.linuxtv.org/patch/39673/ . I've rebased the patches on top of the `base` branch and tested them (https://github.com/intel/intel-iot-refkit/pull/98). The patches appear to improve SR300 support quite a bit, even if some things are still missing.

Would you like to carry the patches already before they are merged upstream?

**Comment by rweight** [comment]
These patches were included in the 4/26/2017 release
