### ISSUE TITLE
kernel OOPS when trying to mount efivarfs

### ISSUE THREAD

**Issue by klihub** [01org/linux-intel-4.9#4]
On RefKit images trying to mount efivarfs results in a kernel oops. Looks like a linux-intel-4.9 problem, switching meta-intel to linux-yocto-4.10 gets rid of this problem. See the attached dmesg dump for the oops. To reproduce
- boot into any image running linux-intel-4.9
- modprobe efivarfs
- mount -t efivarfs none /sys/firmware/efi/efivars

[efivarfs-mount-oops.txt](https://github.com/01org/linux-intel-4.9/files/885818/efivarfs-mount-oops.txt)

**Comment by rweight** [comment]
The fix for this issue was included in 4/13/2017 release.
