### ISSUE TITLE
Joule crashes on suspend

### ISSUE THREAD

**Issue by jlaitine** [01org/linux-intel-4.9#5]
On joule570x, doing "echo freeze > /sys/power/state" essentially crashes the device. We get:
[   70.107914] PM: Syncing filesystems ... done.
[   70.369760] Freezing user space processes ... (elapsed 0.001 seconds) done.
[   70.379293] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.

The display on HDMI goes blank. There is no way to wake up the device; hitting characters to uart doesn't do anything nor does pressing power button. Also inserting SD card, which should generate an interrupt, doesn't do anything.

**Comment by jlaitine** [comment]
More info on this. It was found that the device actually wakes up after 10 seconds after a power button press.

**Comment by jlaitine** [comment]
The root cause for this seems to be whiskey cove irq storms and other misbehaviour, caused by wrong register address calculation in whiskey cove gpio driver. I did this fix for it:

https://github.com/01org/linux-intel-4.9/pull/7

The same fix corrects also problems with usb typec device/host mode switching, as now it is able to receive also these interrupts:
472:          0          9          0          0  bxtwc_irq_chip_level2    8  bxt_wcove_gpio
473:          0          9          0          0  bxtwc_irq_chip_level2    5  wcove_typec

**Comment by jlaitine** [comment]
Here is an easy way to re-produce the issue:

Power on the device with an USB cable connected between a PC and tuchuck development board type-C connector. After boot, monitor /proc/interrupts to see how this interrupt:
  40:        299          0          0          0   IO-APIC   40-fasteoi   intel_pmc_ipc

While the interrupt counts are uncontrollably growing, try to suspend the device with "echo freeze > /sys/power/state". See the device mis-behave.

Another way to approach this is to look at the Whiskey Cove data sheet, if one has one available, and see how the registers are accessed wrongly in the code.

Proper register access is implemented in pull request #7 . Without this, the operation of WC GPIOS is more or less random.

**Comment by pkushwah3** [comment]
comment from Jukka:
This commit has fixed the issue:

commit 2bdfe9d36d1cf6b1a6f1b0e99bd6fdf764c62b6a
 Author: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>
 Date: Mon Jun 26 10:37:04 2017 -0700

UPSTREAM: gpio: gpio-wcove: Fix GPIO control register offset calculation

commit 3a02dc974720cdfcea7fde462bcfc12a180e410f upstream.


Jukka, please close this issue.

**Comment by jlaitine** [comment]
Closed, thanks for the fix
